apiVersion: v1
kind: pod 
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env: 
      - name: conurse
        value: docker
      - name: content
        value: docker

      