apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    iamge: nginx 
    env:
      - name: course
        value: docker
      - name: duartion 
        value: five

      