apiVersion: v1
kind: pod 
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      env: 
      - name: config-map
        course: docker
        time: 8pm
        

      